### ISSUE TITLE
recommendation: better css

### ISSUE THREAD

**Issue by sunnysideup** [colymba/GridFieldBulkEditingTools#218]
Hi

I added this

```css
.bulkManagerOptions.form--no-dividers label.form-check-label input {
    margin-left: 3px;
}
.bulkManagerOptions.form--no-dividers label.form-check-label {
    display: block;
    padding-bottom: 35px;
}
```

to change this:
![image](https://user-images.githubusercontent.com/167154/129466161-ddd55295-c425-437c-8dff-1719dfd35f0f.png)

TO: 
![image](https://user-images.githubusercontent.com/167154/129466168-8ddcf887-b47b-458c-af34-8513f7c8347c.png)
